### ISSUE TITLE
Folder Title is not showing for bigger ones

### ISSUE THREAD

**Issue by sifatefat** [Mods-Center/Miui_Launcher_Mod#7]
If the folder name is here, that would be great, i set the name but in only shows when i expand the folder.
![Screenshot_2023-02-10-22-03-34-685-edit_com miui home](https://user-images.githubusercontent.com/109143536/218138720-3e88b42c-ba55-432d-9fc4-301f146408c7.jpg)

**Comment by Mods-Center** [comment]
@sifatefat Will resolve this issue soon

**Comment by sifatefat** [comment]
Cool! Fixed by todays new release. Great. Thank you again for your amazing work.
